In [1]:
import yfinance as yf
import pandas as pd

# Create ticker object
tesla = yf.Ticker("TSLA")

# Extract historical stock data
tesla_data = tesla.history(period="max")

# Reset the index
tesla_data.reset_index(inplace=True)

# Display first 5 rows
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
url = "https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue"

html_data = requests.get(url).text

In [4]:
soup = BeautifulSoup(html_data, "html.parser")

In [6]:
tesla_revenue = pd.DataFrame(columns=["Date", "Revenue"])

In [7]:
for row in soup.find_all("tbody")[1].find_all("tr"):
    col = row.find_all("td")

    if len(col) != 0:
        date = col[0].text
        revenue = col[1].text

        tesla_revenue.loc[len(tesla_revenue)] = [date, revenue]

IndexError: list index out of range

In [8]:
print(len(soup.find_all("tbody")))

0

In [9]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

url = "https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue"

headers = {
    "User-Agent": "Mozilla/5.0"
}

html_data = requests.get(url, headers=headers).text

soup = BeautifulSoup(html_data, "html.parser")

print(len(soup.find_all("tbody")))

4

In [10]:
tesla_revenue = pd.DataFrame(columns=["Date", "Revenue"])

for row in soup.find_all("tbody")[1].find_all("tr"):
    col = row.find_all("td")

    if len(col) != 0:
        date = col[0].text
        revenue = col[1].text

        tesla_revenue.loc[len(tesla_revenue)] = [date, revenue]

In [11]:
tesla_revenue.head()

         Date  Revenue
0  2026-03-31  $22,387
1  2025-12-31  $24,901
2  2025-09-30  $28,095
3  2025-06-30  $22,496
4  2025-03-31  $19,335

In [12]:
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace(',|\$', "", regex=True)

tesla_revenue.dropna(inplace=True)

tesla_revenue = tesla_revenue[tesla_revenue["Revenue"] != ""]

In [13]:
tesla_revenue.tail()

          Date Revenue
55  2012-06-30      27
56  2012-03-31      30
57  2011-12-31      39
58  2011-09-30      58
59  2011-06-30      58

In [14]:
gme = yf.Ticker("GME")

In [15]:
gme_data = gme.history(period="max")

In [16]:
gme_data.reset_index(inplace=True)

In [17]:
gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620128,1.693350,1.603296,1.691666,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683251,1.687459,1.658002,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615921,1.662210,1.603296,1.662210,6892800,0.0,0.0

In [18]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [19]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html"

html_data_2 = requests.get(url).text

In [20]:
soup = BeautifulSoup(html_data_2, "html.parser")

In [21]:
gme_revenue = pd.DataFrame(columns=["Date", "Revenue"])

In [22]:
for row in soup.find_all("tbody")[1].find_all("tr"):
    col = row.find_all("td")

    if len(col) != 0:
        date = col[0].text
        revenue = col[1].text

        gme_revenue.loc[len(gme_revenue)] = [date, revenue]

In [23]:
gme_revenue["Revenue"] = gme_revenue["Revenue"].str.replace(',|\$', "", regex=True)

gme_revenue.dropna(inplace=True)

gme_revenue = gme_revenue[gme_revenue["Revenue"] != ""]

In [24]:
gme_revenue.tail()

          Date Revenue
57  2006-01-31    1667
58  2005-10-31     534
59  2005-07-31     416
60  2005-04-30     475
61  2005-01-31     709

In [26]:
def make_graph(stock_data, revenue_data, stock):abs
make_graph(tesla_data, tesla_revenue, 'Tesla')

In [27]:
make_graph(gme_data, gme_revenue, 'GameStop')

In [28]:
make_graph

In [29]:
tesla_data.shape
tesla_revenue.shape
tesla_revenue.tail()

          Date Revenue
55  2012-06-30      27
56  2012-03-31      30
57  2011-12-31      39
58  2011-09-30      58
59  2011-06-30      58

In [30]:
make_graph(tesla_data, tesla_revenue, 'Tesla')